config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'hospitals#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'hospitals', to: 'hospitals#index', as: 'hospital_index'
  get 'hospitals/:hospital_id/doctors', to: 'doctors#index', as: 'doctor_index'
  get 'doctors', to: 'doctors#index', as: 'all_doctor_index'
  get 'bookings', to: 'bookings#index', as: 'booking_index'
  get 'bookings/doctor/:doctor_id', to: 'bookings#doctor', as: 'booking_doctor_index'
  get 'booking/new', to: 'bookings#new', as: 'booking_new'
  post 'booking/create', to: 'bookings#create', as: 'booking_create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :doctor
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  belongs_to :hospital

  has_many :bookings
  has_many :schedules
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  has_many :doctors
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :doctor
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
  has_many :schedules
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def fetch_table_data
    ::ListService.new(table_name, selected_column, params[:limit], params[:offset], query_params).process
  end

  def query_params; end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    get_doctor
    return redirect_to doctor_index_path(@doctor.hospital_id), alert: 'No Dctor Found' if @doctor.blank?
    @booking = Booking.new(doctor_id: @doctor.id)
  end

  def index
    @bookings = current_user.bookings
  end

  def doctor
    get_doctor
    @bookings = @doctor.bookings
  end

  def create
    message = BookingService.new(current_user, create_params).create
    if message == 'Success'
      redirect_to booking_index_path
    else
      redirect_to booking_new_path(doctor_id: create_params[:doctor_id]), alert: message
    end
  end

  def create_params
    params.require(:booking).permit(:doctor_id, :booking_time)
  end

  def get_doctor
    @doctor = Doctor.find_by_id(params[:doctor_id])
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  def index
    @doctors = fetch_table_data.includes(:hospital)
  end

  def selected_column
    [:id, :hospital_id, :name]
  end

  def table_name
    "Doctor"
  end

  def query_params
    params.permit(:hospital_id)
  end
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  def index
    @hospitals = fetch_table_data
  end

  def selected_column
    [:id, :name, :address]
  end

  def table_name
    "Hospital"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/views/bookings/doctor.html.haml
%h3
  = @doctor.name
- if @bookings.present?
  %table
    %tr
      %th No
      %th Patient Name
      %th Hospital Name
      %th Booking Time
    - @bookings.each_with_index do |booking, idx|
      %tr
        %td
          = idx + 1
        %td
          = booking.user.email
        %td
          = booking.doctor.hospital.name
        %td
          = booking.booking_time
- else
  No Booking for this doctor yet

app/views/bookings/index.html.haml
%table
  - @bookings.each do |booking|
    %tr
      %td
        = booking.doctor.name
      %td
        = booking.doctor.hospital.name
      %td
        = booking.booking_time

app/views/bookings/new.html.haml
%table
  %tr
    %th
      = "#{@booking.doctor.name} Schedule Time"
  - @booking.doctor.schedules.each do |schedule|
    %tr
      %td
        = "#{schedule.day} From #{schedule.start_time} to #{schedule.end_time} "

%br
%br
%br

= form_for @booking, url: booking_create_path do |f|
  = f.label 'Doctor Name'
  = @booking.doctor.name
  = f.hidden_field :doctor_id
  %br
  %br
  = f.label 'Booking Time'
  = f.datetime_select :booking_time, start_year: Time.now.year
  %br
  %br
  = f.submit

app/views/doctors/index.html.haml
%table
  %tr
    %th ID
    %th Hospital Name
    %th Doctor Name
    %th Booking Doctor
    %th Booking List
  - @doctors.each do |doctor|
    %tr
      %td
        = doctor.id
      %td
        = doctor.hospital.name
      %td
        = doctor.name
      %td
        = link_to 'New Booking', booking_new_path(doctor_id: doctor.id)
      %td
        = link_to 'Booking List', booking_doctor_index_path(doctor_id: doctor.id)

app/views/hospitals/index.html.haml
%table
  %tr
    %th ID
    %th Hospital Name
    %th Hospital Address
    %th Doctor List
  - @hospitals.each do |hospital|
    %tr
      %td
        = hospital.id
      %td
        = hospital.name
      %td
        = hospital.address
      %td
        = link_to 'See List' , doctor_index_path(hospital_id: hospital.id)

app/views/layouts/_navigation.html.haml
%ul.horizontal.gray
  %li
    = link_to "Hospital", hospital_index_path
    = link_to "All Doctor", all_doctor_index_path
    = link_to "My Bookings", booking_index_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HospitalApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/navigation'%>
    <% flash.each do |type, msg| %>
    <div>
      <%= msg %>
    </div>
    <% end %>
    <%= yield %>
  </body>
</html>